# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Prevent Python from writing pyc files and buffer stdout/stderr
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
  && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml .
COPY src/ ./src/
COPY README.md .

# Install Python dependencies
RUN pip install --upgrade pip \
  && pip install --no-cache-dir . \
  && rm -rf /root/.cache/pip

# Expose port if needed (FastMCP defaults to stdio, no port)

# Default command: logging off
ENTRYPOINT ["kv-extractor-mcp-server"]
CMD ["--log=off"]
